openapi: 3.0.0
info:
  title: Age Calculator API
  description: An API to calculate age based on name and birthdate
  version: 1.0.0

servers:
  - url: http://localhost:5000/api
    description: Local development server

components:
  schemas:
    User:
      type: object
      required:
        - name
        - birth_date
      properties:
        name:
          type: string
        birth_date:
          type: string
          format: date
    Age:
      type: object
      required:
        - age
      properties:
        age:
          type: integer
    UserWithAge:
      type: object
      required:
        - name
        - age
      properties:
        name:
          type: string
        age:
          type: integer
    AllUsersWithAge:
      type: object
      required:
        - users
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/UserWithAge'

paths:
  /age:
    post:
      summary: Endpoint to calculate age based on name and birthdate
      description: This endpoint calculates age based on name and birthdate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: A JSON object with the calculated age
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculatedAge'
    get:
      summary: Endpoint to retrieve a list of all names and birthdates
      description: This endpoint retrieves a list of all names and birthdates
      responses:
        '200':
          description: A JSON object with a list of all names and birthdates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllUsers'
  /get_users:
    get:
      summary: Endpoint to retrieve a list of all names and birthdates with age
      description: This endpoint retrieves a list of all names and birthdates with age
      responses:
        '200':
          description: A JSON object with a list of all names and birthdates with age
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllUsersWithAge'
  /calculate_age:
    post:
      summary: Endpoint to calculate age based on name and birthdate
      description: This endpoint calculates age based on name and birthdate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserWithDate'
      responses:
        '200':
          description: A JSON object with the calculated age
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculatedAge'
